---
title: "short R tutorial"
author: "Adler, 2012"
output: pdf_document
---

Following is the R tutorial from Adler, 2012, Chapter 3. I'll verbally explain the steps as we go along but you can always refer to the book for a more detailed explanation.

# Numbers

```{r numbers}
1+2+3

1+2*3

(1+2)*3
```

# Vectors

```{r vectors}
c(0,1,1,2,3,5,8)

1:50

c(1,2,3,4) + c(10,20,30,40)

c(1,2,3,4) * c(10,20,30,40)

c(1,2,3,4) + 1

1/c(1,2,3,4,5)

c(1,2,3,4) + c(10,100)

# this one generates an error message
c(1,2,3,4,5) + c(10,100)
```

# Character Vectors

```{r character vectors}
"Hello world!"

c("Hello world","Hello R")
```

# Functions

```{r functions}
exp(1)

cos(3.141593)

log2(1)

log(x=64,base=4)

log(64,4)
```

# Operators

```{r operators}
17 + 2

2 ^ 10

3 == 4
```

# Variables

```{r variables}
x <- 1

y <- 2

z <- c(x,y)

z

y <- 4

z

j <- c(1:12)

j

j[7]

j[1:6]

j[j %% 3 == 0]

k <- j

k[j %% 3 == 0] <- 'x'

k[j %% 3 == 0] <- 1:4

j <- c(12:1)

j[c(1,6,11)]

j %% 3 == 0

j[j %% 3 == 0]
```

# Assignment operators

```{r assignment operators}
x <- 1

y <- 2

x = y

x

y

x == y

x <- 1

y <- 2

x == y

3 -> z

z
```

# Functions

```{r functions2}
f <- function(x,y) {c(x+1,y+1)}

f(1,2)

f
```

# Data structures

```{r data structures}
a <- array(c(1:12), dim=c(3,4))

a

a[2,2]

v <- c(1:12)

v

m <- matrix(data=c(1:12),nrow=3,ncol=4)

m

w <- array(c(1:18),dim=c(3,3,2))

w

a[1,2]

a[1:2,1:2]

a[1,]

a[,1]

a[1:2,]

a[c(1,3),]

e <- list(thing="hat",size="8.25")

e

e$thing

e[1]

e[[1]]

g <- list("this list references another list",e)

g

# a data frame is a list containing multiple named vectors of the same length

teams <- c("PHI","NYM","FLA","ATL","WSN")

w <- c(92,89,94,72,59)

l <- c(70,73,77,90,102)

nleast <- data.frame(teams,w,l)

nleast

nleast$w

nleast$teams == "FLA"

nleast$l[nleast$teams=="FLA"]
```

# Objects and Classes

```{r objects}
class(teams)

class(w)

class(nleast)

class(class)

# + is a generic function for adding objects
17 + 6

as.Date("2009-09-08") + 7

x <- 1 + 2 + 3 + 4

# When you type the name of an object, R calls print() on it
x
```
